### ISSUE TITLE
Cannot figure out how to install/use on Windows 11

### ISSUE THREAD

**Issue by AnhadSodhi** [csmith/alphabat#1]
Hi there! I recently came across your repo when searching for a solution to check my battery life without using HyperX's terrible NGENUITY software. I have installed go but cannot figure out how to install/run the program. I have tried 'go install github.com/csmith/alphabat@latest' in the bin folder of go and in my disk's root folder. The root folder gave me a little dialog about installing, but I cannot figure out how to run it now. I am unfamiliar with the Go language.

Edit: I copied the source code to my pc and ran it, but gives me exit status 1 every time even though my headset is connected. I have tried doing both 'go run .' and 'go run main.go'.

**Comment by csmith** [comment]
Hey! Yeah, Go can be a little weird if you're not familiar with it. I've opened #2 to release binaries which would save people from having to deal with that :sweat_smile: 

It sounds like you're running it successfully now at least... Exit code 1 means it can't find the USB device for some reason.
I've not actually tried running this on Windows, and don't really have a way to test it myself, so I can only really guess how to proceed.

First I'd try running it as an administrator (i.e., [open a command prompt as an administrator](https://www.bleepingcomputer.com/tutorials/how-to-open-a-windows-11-command-prompt-as-administrator/) then do the same go run command you did before) - if that works then it must be some kind of permissions issue.

If it doesn't work then you could check the hardware IDs used by your dongle. [There are some instructions for how to find them here](https://superuser.com/a/1106248). This code is looking for a vendor ID (`VID`)  of `03f0` and a product id (`PID`) of `098d`. It could be that HyperX changed those at some point if they've made a slight change to the hardware.

Other than those two things, I'm not sure what to suggest. The code in this repo is really simple, but relies on some big libraries for the actual USB HID communication. They say they support Windows, but remotely trying to figure out what's going on if they don't work is a bit beyond me!

**Comment by ShaneMcC** [comment]
I've managed to get it working by building it under WSL2

From a wsl2 prompt:

```
cd /tmp
git clone http://github.com/csmith/alphabat
cd alphabat
sudo apt install mingw-w64 golang-go
go build .
cp /tmp/alphabat/alphabat.exe /mnt/c/temp/alphabat.exe
```

Then it will be in `c:\temp\alphabat.exe` for you to move somewhere else.

**Comment by ShaneMcC** [comment]
Without using WSL2:

You need to install mingw to allow for building with CGO.

In a powershell admin window:
```
choco install -y mingw
```
(There may be other ways to do this.)

In a regular command window get a clone of the repo:
```
cd c:\temp
git clone http://github.com/csmith/alphabat
cd alphabat
```
(Or however else you would get a clone of the repo)

In a command window inside `c:\temp\alphabat`
```
set CGO_ENABLED=1
go build .
```

**Comment by AnhadSodhi** [comment]
It turns out I just cloned the project wrong, works fine now. Thank you both, nevertheless, expecially on the prompt reply. I double-checked the hardware IDs and they are still the same, as of my July 2022 headset.
